# Generated by Django 2.0.3 on 2018-03-25 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail_location',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/thumbnails/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
