# Generated by Django 2.0.3 on 2018-03-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_thumbnail_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='thumbnail_location',
        ),
    ]
