# Generated by Django 2.0.1 on 2018-01-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=120)),
                ('cust_email_address', models.EmailField(max_length=254)),
                ('cust_contact_number', models.IntegerField(max_length=20)),
                ('cust_location', models.CharField(max_length=250)),
                ('cust_inquiry', models.CharField(max_length=1000)),
            ],
        ),
    ]
