# Generated by Django 2.0.1 on 2018-01-17 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20180117_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='cust_contact_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+639191234567'. Up to 13 digits allowed.", regex='^\\+?63?\\d{9-13}$')]),
        ),
    ]
