# Generated by Django 2.0.1 on 2018-02-18 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0005_auto_20180120_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='marked_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
